/* 中文注释：browser/codemap/skills/superpowers 组件规则按安装组件聚合。 */
export const BROWSER_CODEMAP_COMPONENT_RULES = Object.freeze([
  Object.freeze({
    id: 'codemap-component-facade',
    label: 'Codemap Component Facade',
    path: 'scripts/lib/components/codemap.mjs',
    maxLines: 80,
    requiredModules: Object.freeze([
      'scripts/lib/components/codemap/constants.mjs',
      'scripts/lib/components/codemap/paths.mjs',
      'scripts/lib/components/codemap/state-store.mjs',
      'scripts/lib/components/codemap/crg.mjs',
      'scripts/lib/components/codemap/selection.mjs',
      'scripts/lib/components/codemap/instructions.mjs',
      'scripts/lib/components/codemap/mcp-targets.mjs',
      'scripts/lib/components/codemap/opencode-plugin.mjs',
      'scripts/lib/components/codemap/environment.mjs',
      'scripts/lib/components/codemap/install.mjs',
      'scripts/lib/components/codemap/uninstall.mjs',
      'scripts/lib/components/codemap/doctor.mjs',
      'scripts/lib/components/codemap/commands.mjs',
    ]),
  }),
  Object.freeze({
    id: 'codemap-mcp-targets-facade',
    label: 'Codemap MCP Targets Facade',
    path: 'scripts/lib/components/codemap/mcp-targets.mjs',
    maxLines: 80,
    requiredModules: Object.freeze([
      'scripts/lib/components/codemap/mcp-targets/entries.mjs',
      'scripts/lib/components/codemap/mcp-targets/toml.mjs',
      'scripts/lib/components/codemap/mcp-targets/json.mjs',
      'scripts/lib/components/codemap/mcp-targets/formats.mjs',
      'scripts/lib/components/codemap/mcp-targets/targets.mjs',
    ]),
  }),
  Object.freeze({
    id: 'browser-component-facade',
    label: 'Browser Component Facade',
    path: 'scripts/lib/components/browser.mjs',
    maxLines: 80,
    requiredModules: Object.freeze([
      'scripts/lib/components/browser/constants.mjs',
      'scripts/lib/components/browser/shared.mjs',
      'scripts/lib/components/browser/runtime-paths.mjs',
      'scripts/lib/components/browser/mcp-config.mjs',
      'scripts/lib/components/browser/install.mjs',
      'scripts/lib/components/browser/cdp-service.mjs',
      'scripts/lib/components/browser/doctor.mjs',
    ]),
  }),
  Object.freeze({
    id: 'browser-mcp-config-facade',
    label: 'Browser MCP Config Facade',
    path: 'scripts/lib/components/browser/mcp-config.mjs',
    maxLines: 80,
    requiredModules: Object.freeze([
      'scripts/lib/components/browser/mcp-snippet.mjs',
      'scripts/lib/components/browser/mcp-server-builders.mjs',
      'scripts/lib/components/browser/mcp-targets.mjs',
      'scripts/lib/components/browser/mcp-migration.mjs',
    ]),
  }),
  Object.freeze({
    id: 'skills-component-facade',
    label: 'Skills Component Facade',
    path: 'scripts/lib/components/skills.mjs',
    maxLines: 80,
    requiredModules: Object.freeze([
      'scripts/lib/components/skills/constants.mjs',
      'scripts/lib/components/skills/normalizers.mjs',
      'scripts/lib/components/skills/path-utils.mjs',
      'scripts/lib/components/skills/catalog.mjs',
      'scripts/lib/components/skills/safety.mjs',
      'scripts/lib/components/skills/install-targets.mjs',
      'scripts/lib/components/skills/install.mjs',
      'scripts/lib/components/skills/uninstall.mjs',
      'scripts/lib/components/skills/doctor.mjs',
    ]),
  }),
  Object.freeze({
    id: 'superpowers-component-facade',
    label: 'Superpowers Component Facade',
    path: 'scripts/lib/components/superpowers.mjs',
    maxLines: 80,
    requiredModules: Object.freeze([
      'scripts/lib/components/superpowers/constants.mjs',
      'scripts/lib/components/superpowers/clients.mjs',
      'scripts/lib/components/superpowers/claude-plugin.mjs',
      'scripts/lib/components/superpowers/skills.mjs',
      'scripts/lib/components/superpowers/permissions.mjs',
      'scripts/lib/components/superpowers/install.mjs',
      'scripts/lib/components/superpowers/doctor.mjs',
    ]),
  }),
]);
