/* 中文注释：CLI parser/help 规则独立维护，防止入口解析器回到大 if/else 文件。 */
export const CLI_COMPONENT_RULES = Object.freeze([
  Object.freeze({
    id: 'cli-maintenance-parser-facade',
    label: 'CLI Maintenance Parser Facade',
    path: 'scripts/lib/cli/parse-args/maintenance.mjs',
    maxLines: 80,
    requiredModules: Object.freeze([
      'scripts/lib/cli/parse-args/internal.mjs',
      'scripts/lib/cli/parse-args/memo.mjs',
      'scripts/lib/cli/parse-args/perception.mjs',
      'scripts/lib/cli/parse-args/init.mjs',
      'scripts/lib/cli/parse-args/offload.mjs',
      'scripts/lib/cli/parse-args/model-router.mjs',
      'scripts/lib/cli/parse-args/interception.mjs',
    ]),
  }),
  Object.freeze({
    id: 'cli-team-parser-facade',
    label: 'CLI Team Parser Facade',
    path: 'scripts/lib/cli/parse-args/team.mjs',
    maxLines: 80,
    requiredModules: Object.freeze([
      'scripts/lib/cli/parse-args/team/defaults.mjs',
      'scripts/lib/cli/parse-args/team/shared.mjs',
      'scripts/lib/cli/parse-args/team/run.mjs',
      'scripts/lib/cli/parse-args/team/status.mjs',
      'scripts/lib/cli/parse-args/team/history.mjs',
      'scripts/lib/cli/parse-args/team/watchdog.mjs',
      'scripts/lib/cli/parse-args/team/skill-candidates.mjs',
    ]),
  }),
  Object.freeze({
    id: 'cli-top-level-parser-facade',
    label: 'CLI Top-Level Parser Facade',
    path: 'scripts/lib/cli/parse-args/top-level.mjs',
    maxLines: 80,
    requiredModules: Object.freeze([
      'scripts/lib/cli/parse-args/top-level/defaults.mjs',
      'scripts/lib/cli/parse-args/top-level/positionals.mjs',
      'scripts/lib/cli/parse-args/top-level/component-options.mjs',
      'scripts/lib/cli/parse-args/top-level/doctor-options.mjs',
      'scripts/lib/cli/parse-args/top-level/workflow-options.mjs',
      'scripts/lib/cli/parse-args/top-level/release-options.mjs',
    ]),
  }),
  Object.freeze({
    id: 'cli-help-facade',
    label: 'CLI Help Facade',
    path: 'scripts/lib/cli/help.mjs',
    maxLines: 80,
    requiredModules: Object.freeze([
      'scripts/lib/cli/help/root.mjs',
      'scripts/lib/cli/help/codemap.mjs',
      'scripts/lib/cli/help/memo.mjs',
      'scripts/lib/cli/help/commands.mjs',
      'scripts/lib/cli/help/commands/basic.mjs',
      'scripts/lib/cli/help/commands/workflow.mjs',
      'scripts/lib/cli/help/commands/maintenance.mjs',
      'scripts/lib/cli/help/internal.mjs',
    ]),
  }),
]);
