/* 中文注释：harness/interception 规则独立分组，便于长期治理子代理和 solo runtime。 */
export const HARNESS_COMPONENT_RULES = Object.freeze([
  Object.freeze({
    id: 'subagent-runtime-facade',
    label: 'Subagent Runtime Facade',
    path: 'scripts/lib/harness/subagent-runtime.mjs',
    maxLines: 260,
    requiredModules: Object.freeze([
      'scripts/lib/harness/subagent-runtime/constants.mjs',
      'scripts/lib/harness/subagent-runtime/client-args.mjs',
      'scripts/lib/harness/subagent-runtime/phase-job.mjs',
      'scripts/lib/harness/subagent-runtime/phase-output.mjs',
      'scripts/lib/harness/subagent-runtime/phase-blocks.mjs',
      'scripts/lib/harness/subagent-clients/one-shot.mjs',
      'scripts/lib/harness/subagent-clients/invocation-runner.mjs',
      'scripts/lib/harness/subagent-clients/codex-exec.mjs',
      'scripts/lib/harness/subagent-clients/spawn-result.mjs',
    ]),
  }),
  Object.freeze({
    id: 'interception-capability-facade',
    label: 'Interception Capability Facade',
    path: 'scripts/lib/interception/clients/capabilities.mjs',
    maxLines: 120,
    requiredModules: Object.freeze([
      'scripts/lib/interception/mcp/proxy-config.mjs',
      'scripts/lib/interception/mcp/proxy-inspector.mjs',
    ]),
  }),
  Object.freeze({
    id: 'solo-runtime-facade',
    label: 'Solo Runtime Facade',
    path: 'scripts/lib/harness/solo-runtime.mjs',
    maxLines: 80,
    requiredModules: Object.freeze([
      'scripts/lib/harness/solo-runtime/constants.mjs',
      'scripts/lib/harness/solo-runtime/normalizers.mjs',
      'scripts/lib/harness/solo-runtime/backoff.mjs',
      'scripts/lib/harness/solo-runtime/hooks.mjs',
      'scripts/lib/harness/solo-runtime/checkpoint.mjs',
      'scripts/lib/harness/solo-runtime/state.mjs',
      'scripts/lib/harness/solo-runtime/loop.mjs',
    ]),
  }),
  Object.freeze({
    id: 'solo-journal-facade',
    label: 'Solo Journal Facade',
    path: 'scripts/lib/harness/solo-journal.mjs',
    maxLines: 80,
    requiredModules: Object.freeze([
      'scripts/lib/harness/solo-journal/constants.mjs',
      'scripts/lib/harness/solo-journal/normalizers.mjs',
      'scripts/lib/harness/solo-journal/paths.mjs',
      'scripts/lib/harness/solo-journal/io.mjs',
      'scripts/lib/harness/solo-journal/summary.mjs',
      'scripts/lib/harness/solo-journal/control.mjs',
      'scripts/lib/harness/solo-journal/init.mjs',
      'scripts/lib/harness/solo-journal/iteration.mjs',
      'scripts/lib/harness/solo-journal/hooks.mjs',
      'scripts/lib/harness/solo-journal/status.mjs',
    ]),
  }),
  Object.freeze({
    id: 'orchestrator-evidence-facade',
    label: 'Orchestrator Evidence Facade',
    path: 'scripts/lib/harness/orchestrator-evidence.mjs',
    maxLines: 80,
    requiredModules: Object.freeze([
      'scripts/lib/harness/orchestrator-evidence/constants.mjs',
      'scripts/lib/harness/orchestrator-evidence/shared.mjs',
      'scripts/lib/harness/orchestrator-evidence/cost.mjs',
      'scripts/lib/harness/orchestrator-evidence/text.mjs',
      'scripts/lib/harness/orchestrator-evidence/turns.mjs',
      'scripts/lib/harness/orchestrator-evidence/artifact.mjs',
      'scripts/lib/harness/orchestrator-evidence/persist.mjs',
    ]),
  }),
  Object.freeze({
    id: 'orchestrator-runtimes-facade',
    label: 'Orchestrator Runtimes Facade',
    path: 'scripts/lib/harness/orchestrator-runtimes.mjs',
    maxLines: 80,
    requiredModules: Object.freeze([
      'scripts/lib/harness/orchestrator-runtimes/constants.mjs',
      'scripts/lib/harness/orchestrator-runtimes/catalog.mjs',
      'scripts/lib/harness/orchestrator-runtimes/env.mjs',
      'scripts/lib/harness/orchestrator-runtimes/simulation.mjs',
      'scripts/lib/harness/orchestrator-runtimes/handoff-json.mjs',
      'scripts/lib/harness/orchestrator-runtimes/groupchat-adapter.mjs',
      'scripts/lib/harness/orchestrator-runtimes/registry.mjs',
    ]),
  }),
  Object.freeze({
    id: 'groupchat-runtime-facade',
    label: 'GroupChat Runtime Facade',
    path: 'scripts/lib/harness/groupchat-runtime.mjs',
    maxLines: 80,
    requiredModules: Object.freeze([
      'scripts/lib/harness/groupchat-runtime/constants.mjs',
      'scripts/lib/harness/groupchat-runtime/shared.mjs',
      'scripts/lib/harness/groupchat-runtime/history.mjs',
      'scripts/lib/harness/groupchat-runtime/config.mjs',
      'scripts/lib/harness/groupchat-runtime/blueprint-rounds.mjs',
      'scripts/lib/harness/groupchat-runtime/speakers.mjs',
      'scripts/lib/harness/groupchat-runtime/termination.mjs',
      'scripts/lib/harness/groupchat-runtime/prompts.mjs',
      'scripts/lib/harness/groupchat-runtime/execution.mjs',
      'scripts/lib/harness/groupchat-runtime/run.mjs',
    ]),
  }),
  Object.freeze({
    id: 'clarity-gate-facade',
    label: 'Clarity Gate Facade',
    path: 'scripts/lib/harness/clarity-gate.mjs',
    maxLines: 80,
    requiredModules: Object.freeze([
      'scripts/lib/harness/clarity-gate/constants.mjs',
      'scripts/lib/harness/clarity-gate/shared.mjs',
      'scripts/lib/harness/clarity-gate/signals.mjs',
      'scripts/lib/harness/clarity-gate/evaluate.mjs',
      'scripts/lib/harness/clarity-gate/persist.mjs',
    ]),
  }),
]);
