export const COMPONENT_ARCHITECTURE_RULES = Object.freeze([
  Object.freeze({
    id: 'model-router-facade',
    label: 'Model Router Facade',
    path: 'scripts/lib/model-router.mjs',
    maxLines: 120,
    requiredModules: Object.freeze([
      'scripts/lib/model-router/shared.mjs',
      'scripts/lib/model-router/registry.mjs',
      'scripts/lib/model-router/profile.mjs',
      'scripts/lib/model-router/signals.mjs',
      'scripts/lib/model-router/selection.mjs',
      'scripts/lib/model-router/client-cli.mjs',
      'scripts/lib/model-router/routing.mjs',
      'scripts/lib/model-router/reporting.mjs',
      'scripts/lib/model-router/history.mjs',
      'scripts/lib/model-router/command.mjs',
    ]),
  }),
  Object.freeze({
    id: 'codemap-component-facade',
    label: 'Codemap Component Facade',
    path: 'scripts/lib/components/codemap.mjs',
    maxLines: 80,
    requiredModules: Object.freeze([
      'scripts/lib/components/codemap/constants.mjs',
      'scripts/lib/components/codemap/paths.mjs',
      'scripts/lib/components/codemap/state-store.mjs',
      'scripts/lib/components/codemap/crg.mjs',
      'scripts/lib/components/codemap/selection.mjs',
      'scripts/lib/components/codemap/instructions.mjs',
      'scripts/lib/components/codemap/mcp-targets.mjs',
      'scripts/lib/components/codemap/opencode-plugin.mjs',
      'scripts/lib/components/codemap/environment.mjs',
      'scripts/lib/components/codemap/install.mjs',
      'scripts/lib/components/codemap/uninstall.mjs',
      'scripts/lib/components/codemap/doctor.mjs',
      'scripts/lib/components/codemap/commands.mjs',
    ]),
  }),
  Object.freeze({
    id: 'codemap-mcp-targets-facade',
    label: 'Codemap MCP Targets Facade',
    path: 'scripts/lib/components/codemap/mcp-targets.mjs',
    maxLines: 80,
    requiredModules: Object.freeze([
      'scripts/lib/components/codemap/mcp-targets/entries.mjs',
      'scripts/lib/components/codemap/mcp-targets/toml.mjs',
      'scripts/lib/components/codemap/mcp-targets/json.mjs',
      'scripts/lib/components/codemap/mcp-targets/formats.mjs',
      'scripts/lib/components/codemap/mcp-targets/targets.mjs',
    ]),
  }),
  Object.freeze({
    id: 'browser-component-facade',
    label: 'Browser Component Facade',
    path: 'scripts/lib/components/browser.mjs',
    maxLines: 80,
    requiredModules: Object.freeze([
      'scripts/lib/components/browser/constants.mjs',
      'scripts/lib/components/browser/shared.mjs',
      'scripts/lib/components/browser/runtime-paths.mjs',
      'scripts/lib/components/browser/mcp-config.mjs',
      'scripts/lib/components/browser/install.mjs',
      'scripts/lib/components/browser/cdp-service.mjs',
      'scripts/lib/components/browser/doctor.mjs',
    ]),
  }),
  Object.freeze({
    id: 'skills-component-facade',
    label: 'Skills Component Facade',
    path: 'scripts/lib/components/skills.mjs',
    maxLines: 80,
    requiredModules: Object.freeze([
      'scripts/lib/components/skills/constants.mjs',
      'scripts/lib/components/skills/normalizers.mjs',
      'scripts/lib/components/skills/path-utils.mjs',
      'scripts/lib/components/skills/catalog.mjs',
      'scripts/lib/components/skills/safety.mjs',
      'scripts/lib/components/skills/install-targets.mjs',
      'scripts/lib/components/skills/install.mjs',
      'scripts/lib/components/skills/uninstall.mjs',
      'scripts/lib/components/skills/doctor.mjs',
    ]),
  }),
  Object.freeze({
    id: 'superpowers-component-facade',
    label: 'Superpowers Component Facade',
    path: 'scripts/lib/components/superpowers.mjs',
    maxLines: 80,
    requiredModules: Object.freeze([
      'scripts/lib/components/superpowers/constants.mjs',
      'scripts/lib/components/superpowers/clients.mjs',
      'scripts/lib/components/superpowers/claude-plugin.mjs',
      'scripts/lib/components/superpowers/skills.mjs',
      'scripts/lib/components/superpowers/permissions.mjs',
      'scripts/lib/components/superpowers/install.mjs',
      'scripts/lib/components/superpowers/doctor.mjs',
    ]),
  }),
  Object.freeze({
    id: 'platform-process-facade',
    label: 'Platform Process Facade',
    path: 'scripts/lib/platform/process.mjs',
    maxLines: 80,
    requiredModules: Object.freeze([
      'scripts/lib/platform/process/env.mjs',
      'scripts/lib/platform/process/windows-command.mjs',
      'scripts/lib/platform/process/spawn.mjs',
    ]),
  }),
  Object.freeze({
    id: 'native-route-commands-facade',
    label: 'Native Route Commands Facade',
    path: 'scripts/lib/native/route-commands.mjs',
    maxLines: 80,
    requiredModules: Object.freeze([
      'scripts/lib/native/route-commands/constants.mjs',
      'scripts/lib/native/route-commands/selection.mjs',
      'scripts/lib/native/route-commands/render.mjs',
      'scripts/lib/native/route-commands/io.mjs',
      'scripts/lib/native/route-commands/sync.mjs',
    ]),
  }),
  Object.freeze({
    id: 'native-sync-facade',
    label: 'Native Sync Facade',
    path: 'scripts/lib/native/sync.mjs',
    maxLines: 80,
    requiredModules: Object.freeze([
      'scripts/lib/native/sync/constants.mjs',
      'scripts/lib/native/sync/fs-ops.mjs',
      'scripts/lib/native/sync/operations.mjs',
      'scripts/lib/native/sync/apply.mjs',
      'scripts/lib/native/sync/run.mjs',
    ]),
  }),
  Object.freeze({
    id: 'native-doctor-facade',
    label: 'Native Doctor Facade',
    path: 'scripts/lib/native/doctor.mjs',
    maxLines: 80,
    requiredModules: Object.freeze([
      'scripts/lib/native/doctor/shared.mjs',
      'scripts/lib/native/doctor/inspect-operation.mjs',
      'scripts/lib/native/doctor/inspect-client.mjs',
      'scripts/lib/native/doctor/check.mjs',
      'scripts/lib/native/doctor/report.mjs',
      'scripts/lib/native/doctor/run.mjs',
    ]),
  }),
  Object.freeze({
    id: 'cli-help-facade',
    label: 'CLI Help Facade',
    path: 'scripts/lib/cli/help.mjs',
    maxLines: 80,
    requiredModules: Object.freeze([
      'scripts/lib/cli/help/root.mjs',
      'scripts/lib/cli/help/codemap.mjs',
      'scripts/lib/cli/help/memo.mjs',
      'scripts/lib/cli/help/commands.mjs',
      'scripts/lib/cli/help/commands/basic.mjs',
      'scripts/lib/cli/help/commands/workflow.mjs',
      'scripts/lib/cli/help/commands/maintenance.mjs',
      'scripts/lib/cli/help/internal.mjs',
    ]),
  }),
  Object.freeze({
    id: 'subagent-runtime-facade',
    label: 'Subagent Runtime Facade',
    path: 'scripts/lib/harness/subagent-runtime.mjs',
    maxLines: 260,
    requiredModules: Object.freeze([
      'scripts/lib/harness/subagent-runtime/constants.mjs',
      'scripts/lib/harness/subagent-runtime/client-args.mjs',
      'scripts/lib/harness/subagent-runtime/phase-job.mjs',
      'scripts/lib/harness/subagent-runtime/phase-output.mjs',
      'scripts/lib/harness/subagent-runtime/phase-blocks.mjs',
      'scripts/lib/harness/subagent-clients/one-shot.mjs',
      'scripts/lib/harness/subagent-clients/invocation-runner.mjs',
      'scripts/lib/harness/subagent-clients/codex-exec.mjs',
      'scripts/lib/harness/subagent-clients/spawn-result.mjs',
    ]),
  }),
  Object.freeze({
    id: 'solo-runtime-facade',
    label: 'Solo Runtime Facade',
    path: 'scripts/lib/harness/solo-runtime.mjs',
    maxLines: 80,
    requiredModules: Object.freeze([
      'scripts/lib/harness/solo-runtime/constants.mjs',
      'scripts/lib/harness/solo-runtime/normalizers.mjs',
      'scripts/lib/harness/solo-runtime/backoff.mjs',
      'scripts/lib/harness/solo-runtime/hooks.mjs',
      'scripts/lib/harness/solo-runtime/checkpoint.mjs',
      'scripts/lib/harness/solo-runtime/state.mjs',
      'scripts/lib/harness/solo-runtime/loop.mjs',
    ]),
  }),
  Object.freeze({
    id: 'hud-state-facade',
    label: 'HUD State Facade',
    path: 'scripts/lib/hud/state.mjs',
    maxLines: 80,
    requiredModules: Object.freeze([
      'scripts/lib/hud/state/shared.mjs',
      'scripts/lib/hud/state/providers.mjs',
      'scripts/lib/hud/state/quality-gate.mjs',
      'scripts/lib/hud/state/dispatch-insights.mjs',
      'scripts/lib/hud/state/dispatch-progress.mjs',
      'scripts/lib/hud/state/io.mjs',
      'scripts/lib/hud/state/sessions.mjs',
      'scripts/lib/hud/state/artifacts.mjs',
      'scripts/lib/hud/state/commands.mjs',
      'scripts/lib/hud/state/compose.mjs',
    ]),
  }),
  Object.freeze({
    id: 'hud-state-artifacts-facade',
    label: 'HUD State Artifacts Facade',
    path: 'scripts/lib/hud/state/artifacts.mjs',
    maxLines: 80,
    requiredModules: Object.freeze([
      'scripts/lib/hud/state/artifacts/cache.mjs',
      'scripts/lib/hud/state/artifacts/dispatch.mjs',
      'scripts/lib/hud/state/artifacts/skill-candidates.mjs',
    ]),
  }),
  Object.freeze({
    id: 'hud-render-facade',
    label: 'HUD Render Facade',
    path: 'scripts/lib/hud/render.mjs',
    maxLines: 180,
    requiredModules: Object.freeze([
      'scripts/lib/hud/render/shared.mjs',
      'scripts/lib/hud/render/telemetry.mjs',
      'scripts/lib/hud/render/harness.mjs',
      'scripts/lib/hud/render/dispatch.mjs',
      'scripts/lib/hud/render/watchdog.mjs',
      'scripts/lib/hud/render/quality.mjs',
      'scripts/lib/hud/render/skill-candidate.mjs',
      'scripts/lib/hud/render/messages.mjs',
    ]),
  }),
]);
