export const LIFECYCLE_ARCHITECTURE_RULES = Object.freeze([
  Object.freeze({
    id: 'lifecycle-options-facade',
    label: 'Lifecycle Options Facade',
    path: 'scripts/lib/lifecycle/options.mjs',
    maxLines: 80,
    requiredModules: Object.freeze([
      'scripts/lib/lifecycle/options/constants.mjs',
      'scripts/lib/lifecycle/options/defaults.mjs',
      'scripts/lib/lifecycle/options/normalizers.mjs',
    ]),
  }),
  Object.freeze({
    id: 'lifecycle-quality-gate-facade',
    label: 'Lifecycle Quality Gate Facade',
    path: 'scripts/lib/lifecycle/quality-gate.mjs',
    maxLines: 80,
    requiredModules: Object.freeze([
      'scripts/lib/lifecycle/quality-gate/constants.mjs',
      'scripts/lib/lifecycle/quality-gate/commands.mjs',
      'scripts/lib/lifecycle/quality-gate/release-thresholds.mjs',
      'scripts/lib/lifecycle/quality-gate/options.mjs',
      'scripts/lib/lifecycle/quality-gate/runner.mjs',
    ]),
  }),
  Object.freeze({
    id: 'doctor-aggregate-facade',
    label: 'Doctor Aggregate Facade',
    path: 'scripts/lib/doctor/aggregate.mjs',
    maxLines: 320,
    requiredModules: Object.freeze([
      'scripts/lib/doctor/aggregate/reporting.mjs',
      'scripts/lib/doctor/aggregate/native-only.mjs',
    ]),
  }),
  Object.freeze({
    id: 'doctor-security-config-facade',
    label: 'Doctor Security Config Facade',
    path: 'scripts/doctor-security-config.mjs',
    maxLines: 80,
    requiredModules: Object.freeze([
      'scripts/lib/doctor/security-config/args.mjs',
      'scripts/lib/doctor/security-config/files.mjs',
      'scripts/lib/doctor/security-config/patterns.mjs',
      'scripts/lib/doctor/security-config/run.mjs',
    ]),
  }),
  Object.freeze({
    id: 'harness-orchestrator-facade',
    label: 'Harness Orchestrator Facade',
    path: 'scripts/lib/harness/orchestrator.mjs',
    maxLines: 320,
    requiredModules: Object.freeze([
      'scripts/lib/harness/orchestrator/shared.mjs',
      'scripts/lib/harness/orchestrator/blueprints.mjs',
      'scripts/lib/harness/orchestrator/normalizers.mjs',
      'scripts/lib/harness/orchestrator/work-items.mjs',
      'scripts/lib/harness/orchestrator/plan.mjs',
      'scripts/lib/harness/orchestrator/local-jobs.mjs',
      'scripts/lib/harness/orchestrator/local-dispatch-plan.mjs',
      'scripts/lib/harness/orchestrator/handoffs.mjs',
      'scripts/lib/harness/orchestrator/local-execution.mjs',
      'scripts/lib/harness/orchestrator/dispatch-policy.mjs',
      'scripts/lib/harness/orchestrator/report-wrapper.mjs',
      'scripts/lib/harness/orchestrator/report.mjs',
      'scripts/lib/harness/orchestrator/executor-capabilities.mjs',
    ]),
  }),
  Object.freeze({
    id: 'learn-eval-facade',
    label: 'Learn Eval Facade',
    path: 'scripts/lib/harness/learn-eval.mjs',
    maxLines: 320,
    requiredModules: Object.freeze([
      'scripts/lib/harness/learn-eval/io.mjs',
      'scripts/lib/harness/learn-eval/report.mjs',
      'scripts/lib/harness/learn-eval/recommendations.mjs',
      'scripts/lib/harness/learn-eval/recommendations/shared.mjs',
      'scripts/lib/harness/learn-eval/recommendations/actions.mjs',
      'scripts/lib/harness/learn-eval/recommendations/factories.mjs',
      'scripts/lib/harness/learn-eval/recommendations/hindsight-drafts.mjs',
      'scripts/lib/harness/learn-eval/recommendations/build.mjs',
    ]),
  }),
  Object.freeze({
    id: 'hindsight-eval-facade',
    label: 'Hindsight Eval Facade',
    path: 'scripts/lib/harness/hindsight-eval.mjs',
    maxLines: 80,
    requiredModules: Object.freeze([
      'scripts/lib/harness/hindsight-eval/shared.mjs',
      'scripts/lib/harness/hindsight-eval/cache.mjs',
      'scripts/lib/harness/hindsight-eval/extract.mjs',
      'scripts/lib/harness/hindsight-eval/lessons.mjs',
      'scripts/lib/harness/hindsight-eval/io.mjs',
      'scripts/lib/harness/hindsight-eval/run.mjs',
    ]),
  }),
  Object.freeze({
    id: 'lifecycle-orchestrate-facade',
    label: 'Lifecycle Orchestrate Facade',
    path: 'scripts/lib/lifecycle/orchestrate.mjs',
    maxLines: 320,
    requiredModules: Object.freeze([
      'scripts/lib/lifecycle/orchestrate/shared.mjs',
      'scripts/lib/lifecycle/orchestrate/live-capability-guard.mjs',
      'scripts/lib/lifecycle/orchestrate/retry-blocked.mjs',
      'scripts/lib/lifecycle/orchestrate/release-guard.mjs',
      'scripts/lib/lifecycle/orchestrate/preflight.mjs',
      'scripts/lib/lifecycle/orchestrate/overlay.mjs',
      'scripts/lib/lifecycle/orchestrate/retry-replay.mjs',
      'scripts/lib/lifecycle/orchestrate/plan.mjs',
      'scripts/lib/lifecycle/orchestrate/runtime-capability-guard.mjs',
      'scripts/lib/lifecycle/orchestrate/post-dispatch-report.mjs',
    ]),
  }),
  Object.freeze({
    id: 'lifecycle-harness-facade',
    label: 'Lifecycle Harness Facade',
    path: 'scripts/lib/lifecycle/harness.mjs',
    maxLines: 80,
    requiredModules: Object.freeze([
      'scripts/lib/lifecycle/harness/shared.mjs',
      'scripts/lib/lifecycle/harness/session.mjs',
      'scripts/lib/lifecycle/harness/dry-run.mjs',
      'scripts/lib/lifecycle/harness/status.mjs',
      'scripts/lib/lifecycle/harness/prompt.mjs',
      'scripts/lib/lifecycle/harness/execute-turn.mjs',
      'scripts/lib/lifecycle/harness/worktree.mjs',
      'scripts/lib/lifecycle/harness/hooks.mjs',
      'scripts/lib/lifecycle/harness/commands.mjs',
    ]),
  }),
  Object.freeze({
    id: 'team-ops-facade',
    label: 'Team Ops Facade',
    path: 'scripts/lib/lifecycle/team-ops.mjs',
    maxLines: 80,
    requiredModules: Object.freeze([
      'scripts/lib/lifecycle/team-ops/shared.mjs',
      'scripts/lib/lifecycle/team-ops/status-options.mjs',
      'scripts/lib/lifecycle/team-ops/status-artifacts.mjs',
      'scripts/lib/lifecycle/team-ops/status.mjs',
      'scripts/lib/lifecycle/team-ops/history-format.mjs',
      'scripts/lib/lifecycle/team-ops/history-summary.mjs',
      'scripts/lib/lifecycle/team-ops/history.mjs',
      'scripts/lib/lifecycle/team-ops/skill-candidates.mjs',
    ]),
  }),
  Object.freeze({
    id: 'contextdb-shell-bridge-facade',
    label: 'ContextDB Shell Bridge Facade',
    path: 'scripts/contextdb-shell-bridge.mjs',
    maxLines: 80,
    requiredModules: Object.freeze([
      'scripts/lib/contextdb/shell-bridge/constants.mjs',
      'scripts/lib/contextdb/shell-bridge/shared.mjs',
      'scripts/lib/contextdb/shell-bridge/cli.mjs',
      'scripts/lib/contextdb/shell-bridge/code-home.mjs',
      'scripts/lib/contextdb/shell-bridge/privacy.mjs',
      'scripts/lib/contextdb/shell-bridge/workspace.mjs',
      'scripts/lib/contextdb/shell-bridge/prompts.mjs',
      'scripts/lib/contextdb/shell-bridge/process-runner.mjs',
      'scripts/lib/contextdb/shell-bridge/context-index.mjs',
      'scripts/lib/contextdb/shell-bridge/debug.mjs',
      'scripts/lib/contextdb/shell-bridge/main.mjs',
    ]),
  }),
  Object.freeze({
    id: 'memo-cli-facade',
    label: 'Memo CLI Facade',
    path: 'scripts/lib/memo/memo.mjs',
    maxLines: 80,
    requiredModules: Object.freeze([
      'scripts/lib/memo/cli/constants.mjs',
      'scripts/lib/memo/cli/shared.mjs',
      'scripts/lib/memo/cli/workspace-state.mjs',
      'scripts/lib/memo/cli/records.mjs',
      'scripts/lib/memo/cli/legacy.mjs',
      'scripts/lib/memo/cli/storage-api.mjs',
      'scripts/lib/memo/cli/rendering.mjs',
      'scripts/lib/memo/cli/capacity.mjs',
      'scripts/lib/memo/cli/flags.mjs',
      'scripts/lib/memo/cli/gui.mjs',
      'scripts/lib/memo/cli/run.mjs',
      'scripts/lib/memo/cli/commands/storage.mjs',
      'scripts/lib/memo/cli/commands/space.mjs',
      'scripts/lib/memo/cli/commands/persona.mjs',
      'scripts/lib/memo/cli/commands/pin.mjs',
      'scripts/lib/memo/cli/commands/events.mjs',
    ]),
  }),
  Object.freeze({
    id: 'memo-storage-facade',
    label: 'Memo Storage Facade',
    path: 'scripts/lib/memo/storage.mjs',
    maxLines: 80,
    requiredModules: Object.freeze([
      'scripts/lib/memo/storage/constants.mjs',
      'scripts/lib/memo/storage/paths.mjs',
      'scripts/lib/memo/storage/fs-io.mjs',
      'scripts/lib/memo/storage/normalizers.mjs',
      'scripts/lib/memo/storage/config.mjs',
      'scripts/lib/memo/storage/events-read.mjs',
      'scripts/lib/memo/storage/events-write.mjs',
      'scripts/lib/memo/storage/query.mjs',
      'scripts/lib/memo/storage/pinned.mjs',
      'scripts/lib/memo/storage/derived.mjs',
      'scripts/lib/memo/storage/migration.mjs',
      'scripts/lib/memo/storage/status.mjs',
      'scripts/lib/memo/storage/doctor.mjs',
    ]),
  }),
]);
