export const RL_ARCHITECTURE_RULES = Object.freeze([
  Object.freeze({
    id: 'rl-shell-schema-facade',
    label: 'RL Shell Schema Facade',
    path: 'scripts/lib/rl-shell-v1/schema.mjs',
    maxLines: 80,
    requiredModules: Object.freeze([
      'scripts/lib/rl-shell-v1/schema/constants.mjs',
      'scripts/lib/rl-shell-v1/schema/assertions.mjs',
      'scripts/lib/rl-shell-v1/schema/action-observation.mjs',
      'scripts/lib/rl-shell-v1/schema/task-teacher.mjs',
      'scripts/lib/rl-shell-v1/schema/episode.mjs',
      'scripts/lib/rl-shell-v1/schema/run-summary.mjs',
    ]),
  }),
  Object.freeze({
    id: 'rl-shell-temp-runner-facade',
    label: 'RL Shell Temp Runner Facade',
    path: 'scripts/lib/rl-shell-v1/temp-runner.mjs',
    maxLines: 80,
    requiredModules: Object.freeze([
      'scripts/lib/rl-shell-v1/temp-runner/policy.mjs',
      'scripts/lib/rl-shell-v1/temp-runner/text.mjs',
      'scripts/lib/rl-shell-v1/temp-runner/observations.mjs',
      'scripts/lib/rl-shell-v1/temp-runner/workspace.mjs',
      'scripts/lib/rl-shell-v1/temp-runner/command.mjs',
      'scripts/lib/rl-shell-v1/temp-runner/no-progress.mjs',
      'scripts/lib/rl-shell-v1/temp-runner/patch.mjs',
      'scripts/lib/rl-shell-v1/temp-runner/actions.mjs',
      'scripts/lib/rl-shell-v1/temp-runner/verification.mjs',
    ]),
  }),
  Object.freeze({
    id: 'rl-core-trainer-facade',
    label: 'RL Core Trainer Facade',
    path: 'scripts/lib/rl-core/trainer.mjs',
    maxLines: 80,
    requiredModules: Object.freeze([
      'scripts/lib/rl-core/trainer/core.mjs',
      'scripts/lib/rl-core/trainer/config.mjs',
      'scripts/lib/rl-core/trainer/losses.mjs',
      'scripts/lib/rl-core/trainer/bandit-state.mjs',
      'scripts/lib/rl-core/trainer/bandit.mjs',
      'scripts/lib/rl-core/trainer/ppo.mjs',
      'scripts/lib/rl-core/trainer/update.mjs',
    ]),
  }),
  Object.freeze({
    id: 'rl-core-campaign-controller-facade',
    label: 'RL Core Campaign Controller Facade',
    path: 'scripts/lib/rl-core/campaign-controller.mjs',
    maxLines: 80,
    requiredModules: Object.freeze([
      'scripts/lib/rl-core/campaign-controller/ids.mjs',
      'scripts/lib/rl-core/campaign-controller/epoch-state.mjs',
      'scripts/lib/rl-core/campaign-controller/outcome.mjs',
      'scripts/lib/rl-core/campaign-controller/runtime-state.mjs',
      'scripts/lib/rl-core/campaign-controller/episode-source.mjs',
      'scripts/lib/rl-core/campaign-controller/collection.mjs',
      'scripts/lib/rl-core/campaign-controller/monitoring.mjs',
      'scripts/lib/rl-core/campaign-controller/run.mjs',
    ]),
  }),
  Object.freeze({
    id: 'rl-shell-run-orchestrator-facade',
    label: 'RL Shell Run Orchestrator Facade',
    path: 'scripts/lib/rl-shell-v1/run-orchestrator.mjs',
    maxLines: 80,
    requiredModules: Object.freeze([
      'scripts/lib/rl-shell-v1/run-orchestrator/helpers.mjs',
      'scripts/lib/rl-shell-v1/run-orchestrator/episode-record.mjs',
      'scripts/lib/rl-shell-v1/run-orchestrator/training-run.mjs',
      'scripts/lib/rl-shell-v1/run-orchestrator/shadow-eval.mjs',
      'scripts/lib/rl-shell-v1/run-orchestrator/campaign.mjs',
    ]),
  }),
  Object.freeze({
    id: 'rl-orchestrator-decision-runner-facade',
    label: 'RL Orchestrator Decision Runner Facade',
    path: 'scripts/lib/rl-orchestrator-v1/decision-runner.mjs',
    maxLines: 80,
    requiredModules: Object.freeze([
      'scripts/lib/rl-orchestrator-v1/decision-runner/shared.mjs',
      'scripts/lib/rl-orchestrator-v1/decision-runner/evidence.mjs',
      'scripts/lib/rl-orchestrator-v1/decision-runner/real-harness.mjs',
    ]),
  }),
  Object.freeze({
    id: 'rl-orchestrator-policy-release-gate-facade',
    label: 'RL Orchestrator Policy Release Gate Facade',
    path: 'scripts/lib/rl-orchestrator-v1/policy-release-gate.mjs',
    maxLines: 80,
    requiredModules: Object.freeze([
      'scripts/lib/rl-orchestrator-v1/policy-release-gate/shared.mjs',
      'scripts/lib/rl-orchestrator-v1/policy-release-gate/config.mjs',
      'scripts/lib/rl-orchestrator-v1/policy-release-gate/state.mjs',
      'scripts/lib/rl-orchestrator-v1/policy-release-gate/route.mjs',
      'scripts/lib/rl-orchestrator-v1/policy-release-gate/evolution.mjs',
    ]),
  }),
  Object.freeze({
    id: 'rl-mixed-run-orchestrator-facade',
    label: 'RL Mixed Run Orchestrator Facade',
    path: 'scripts/lib/rl-mixed-v1/run-orchestrator.mjs',
    maxLines: 320,
    requiredModules: Object.freeze([
      'scripts/lib/rl-mixed-v1/contextdb-summary.mjs',
      'scripts/lib/rl-mixed-v1/shared.mjs',
      'scripts/lib/rl-mixed-v1/reward-config.mjs',
      'scripts/lib/rl-mixed-v1/reward-tuning.mjs',
      'scripts/lib/rl-mixed-v1/reward.mjs',
      'scripts/lib/rl-mixed-v1/control.mjs',
      'scripts/lib/rl-mixed-v1/shell-adapter.mjs',
      'scripts/lib/rl-mixed-v1/adapters.mjs',
      'scripts/lib/rl-mixed-v1/trajectory.mjs',
      'scripts/lib/rl-mixed-v1/epoch.mjs',
      'scripts/lib/rl-mixed-v1/campaign.mjs',
      'scripts/lib/rl-mixed-v1/campaign/setup.mjs',
      'scripts/lib/rl-mixed-v1/campaign/collection.mjs',
      'scripts/lib/rl-mixed-v1/campaign/training.mjs',
      'scripts/lib/rl-mixed-v1/campaign/monitoring.mjs',
      'scripts/lib/rl-mixed-v1/campaign/epoch-transition.mjs',
      'scripts/lib/rl-mixed-v1/campaign/results.mjs',
      'scripts/lib/rl-mixed-v1/policy/constants.mjs',
      'scripts/lib/rl-mixed-v1/policy/io.mjs',
      'scripts/lib/rl-mixed-v1/policy/ope.mjs',
      'scripts/lib/rl-mixed-v1/policy/index.mjs',
      'scripts/lib/rl-mixed-v1/policy/checkpoint.mjs',
      'scripts/lib/rl-mixed-v1/evaluation.mjs',
    ]),
  }),
]);
