export const RL_ARCHITECTURE_RULES = Object.freeze([
  Object.freeze({
    id: 'rl-mixed-run-orchestrator-facade',
    label: 'RL Mixed Run Orchestrator Facade',
    path: 'scripts/lib/rl-mixed-v1/run-orchestrator.mjs',
    maxLines: 320,
    requiredModules: Object.freeze([
      'scripts/lib/rl-mixed-v1/contextdb-summary.mjs',
      'scripts/lib/rl-mixed-v1/shared.mjs',
      'scripts/lib/rl-mixed-v1/reward-config.mjs',
      'scripts/lib/rl-mixed-v1/reward-tuning.mjs',
      'scripts/lib/rl-mixed-v1/reward.mjs',
      'scripts/lib/rl-mixed-v1/control.mjs',
      'scripts/lib/rl-mixed-v1/shell-adapter.mjs',
      'scripts/lib/rl-mixed-v1/adapters.mjs',
      'scripts/lib/rl-mixed-v1/trajectory.mjs',
      'scripts/lib/rl-mixed-v1/epoch.mjs',
      'scripts/lib/rl-mixed-v1/campaign.mjs',
      'scripts/lib/rl-mixed-v1/campaign/setup.mjs',
      'scripts/lib/rl-mixed-v1/campaign/collection.mjs',
      'scripts/lib/rl-mixed-v1/campaign/training.mjs',
      'scripts/lib/rl-mixed-v1/campaign/monitoring.mjs',
      'scripts/lib/rl-mixed-v1/campaign/epoch-transition.mjs',
      'scripts/lib/rl-mixed-v1/campaign/results.mjs',
      'scripts/lib/rl-mixed-v1/policy/constants.mjs',
      'scripts/lib/rl-mixed-v1/policy/io.mjs',
      'scripts/lib/rl-mixed-v1/policy/ope.mjs',
      'scripts/lib/rl-mixed-v1/policy/index.mjs',
      'scripts/lib/rl-mixed-v1/policy/checkpoint.mjs',
      'scripts/lib/rl-mixed-v1/evaluation.mjs',
    ]),
  }),
]);
