/* 中文注释：release-status 的默认趋势阈值和环境变量名集中维护，避免渲染/计算模块重复定义。 */
export const HISTORY_TREND_FAILURE_DELTA_WARN = 0.05;
export const HISTORY_TREND_FALLBACK_DELTA_WARN = 0.03;
export const HISTORY_TREND_FAILURE_DELTA_WARN_ENV = 'AIOS_RELEASE_TREND_WOW_FAILURE_DELTA_WARN';
export const HISTORY_TREND_FALLBACK_DELTA_WARN_ENV = 'AIOS_RELEASE_TREND_WOW_FALLBACK_DELTA_WARN';
export const HISTORY_TREND_FAILURE_DELTA_WARN_ENV_ALIAS = 'AIOS_RELEASE_WOW_FAILURE_RATE_DELTA_WARN';
export const HISTORY_TREND_FALLBACK_DELTA_WARN_ENV_ALIAS = 'AIOS_RELEASE_WOW_FALLBACK_RATE_DELTA_WARN';
