export const EXECUTION_COMMAND_SPECS = [
  {
    name: 'harness',
    description: 'Solo overnight harness with run journal and resume controls',
    options: [
      ['--objective <text>', 'Objective for a new harness run'],
      ['--session <id>', 'ContextDB session id'],
      ['--workspace <path>', 'Workspace root'],
      ['--provider <provider>', 'Solo harness provider'],
      ['--profile <profile>', 'Harness profile'],
      ['--worktree', 'Use isolated git worktree'],
      ['--base-ref <ref>', 'Base ref for worktree mode'],
      ['--max-iterations <n>', 'Iteration budget'],
      ['--dry-run', 'Do not invoke provider'],
      ['--hooks', 'Enable lifecycle hooks'],
      ['--no-hooks', 'Disable lifecycle hooks'],
      ['--reason <text>', 'Stop reason'],
      ['--json', 'Output JSON'],
    ],
  },
  {
    name: 'hud',
    description: 'Show ContextDB and dispatch HUD',
    options: [
      ['--session <id>', 'ContextDB session id'],
      ['--workspace <path>', 'Workspace root'],
      ['--provider <provider>', 'Provider'],
      ['--preset <preset>', 'Rendering preset'],
      ['--watch', 'Refresh display'],
      ['--fast', 'Fast watch mode'],
      ['--no-fast', 'Disable fast watch mode'],
      ['--watchdog', 'Include watchdog decision'],
      ['--show-skill-candidates [view]', 'Show skill candidates'],
      ['--skill-candidate-view <view>', 'Skill candidate rendering mode'],
      ['--skill-candidate-limit <n>', 'Skill candidate row limit'],
      ['--draft-id <id>', 'Filter by draft target id'],
      ['--export-skill-candidate-patch-template', 'Export apply_patch templates'],
      ['--interval-ms <n>', 'Watch refresh interval'],
      ['--json', 'Output JSON'],
    ],
  },
];
