/* 中文注释：CLI 规格声明工具输出策略，让帮助文案和分发逻辑共享同一事实源。 */
export const TOOL_OUTPUT_COMMAND_SPECS = [
  {
    name: 'model-router',
    description: 'Route tasks to configured model profiles',
    options: [
      ['--task <text>', 'Task prompt'],
      ['--prompt <text>', 'Task prompt alias'],
      ['--task-type <type>', 'Task type'],
      ['--format <format>', 'Output format'],
      ['--profile <profile>', 'Routing profile'],
      ['--explain', 'Explain routing decision'],
      ['--json', 'Output JSON'],
      ['--workspace <path>', 'Workspace root'],
    ],
  },
  {
    name: 'perception',
    description: 'Content outcome recording and insight generation',
    options: [
      ['--space <name>', 'Workspace memory space'],
      ['--format <format>', 'Output format'],
      ['--json', 'Output JSON'],
      ['--dry-run', 'Preview without storing'],
      ['--content-id <id>', 'Content identifier'],
      ['--platform <name>', 'Platform name'],
      ['--content-type <type>', 'Content type'],
      ['--title <text>', 'Content title'],
      ['--publish-time <iso>', 'Publish timestamp'],
      ['--snapshot-window <duration>', 'Metrics snapshot window'],
      ['--metrics <json>', 'Metrics JSON'],
      ['--context <json>', 'Context JSON'],
      ['--max-chars <n>', 'Maximum output characters'],
      ['--min-sample <n>', 'Minimum sample size'],
      ['--workspace <path>', 'Workspace root'],
    ],
  },
  {
    name: 'refs',
    description: 'Search and read offloaded tool-output refs',
    options: [
      ['--session <id>', 'Offload session id'],
      ['--storage <backend>', 'Storage backend'],
      ['--workspace <path>', 'Workspace root'],
      ['--limit <n>', 'Result limit'],
      ['--keep-days <n>', 'Prune retention window'],
    ],
  },
  {
    name: 'canvas',
    description: 'Show Mermaid task canvas for offloaded tool calls',
    options: [
      ['--session <id>', 'Offload session id'],
      ['--format <format>', 'Output format'],
      ['--input <path>', 'JSONL tool-event log'],
      ['--input-path <path>', 'JSONL tool-event log'],
      ['--client <client>', 'Client id'],
      ['--storage <backend>', 'Storage backend'],
      ['--workspace <path>', 'Workspace root'],
    ],
  },
  {
    name: 'interception',
    description: 'RTK/Caveman-style interception proof, MCP proxy repair, and metrics',
    options: [
      ['--session <id>', 'Proof session id'],
      ['--json', 'Output JSON'],
      ['--fix', 'Repair MCP proxy routing before proof'],
      ['--dry-run', 'Preview repair actions without writing configs'],
      ['--workspace <path>', 'Workspace root'],
    ],
  },
];
