export const WORKFLOW_COMMAND_SPECS = [
  {
    name: 'orchestrate',
    description: 'Preview reusable subagent workflow blueprints',
    options: [
      ['--task <title>', 'Task title'],
      ['--context <summary>', 'Context summary'],
      ['--plan <path>', 'Plan artifact path'],
      ['--session <id>', 'ContextDB session id'],
      ['--limit <n>', 'Checkpoint inspection limit'],
      ['--recommendation <id>', 'Pinned recommendation id'],
      ['--dispatch <mode>', 'Dispatch mode'],
      ['--execute <mode>', 'Execution mode'],
      ['--force', 'Override live safety guards'],
      ['--preflight <mode>', 'Preflight mode'],
      ['--format <format>', 'Output format'],
    ],
  },
  {
    name: 'team',
    description: 'One-click multi-client live team runtime',
    options: [
      ['--workers <n>', 'Team worker concurrency'],
      ['--provider <provider>', 'Provider: codex, claude, gemini'],
      ['--blueprint <name>', 'Workflow blueprint'],
      ['--task <title>', 'Task title'],
      ['--context <summary>', 'Context summary'],
      ['--plan <path>', 'Plan artifact path'],
      ['--session <id>', 'ContextDB session id'],
      ['--resume <id>', 'Resume a prior session'],
      ['--limit <n>', 'Result limit'],
      ['--recommendation <id>', 'Pinned recommendation id'],
      ['--preflight <mode>', 'Preflight mode'],
      ['--retry-blocked', 'Replay blocked jobs'],
      ['--force', 'Override safety guards'],
      ['--format <format>', 'Output format'],
      ['--dry-run', 'Local dispatch dry-run'],
      ['--live', 'Force live execution'],
      ['--watch', 'Refresh status display'],
      ['--json', 'Output JSON'],
      ['--watchdog', 'Include watchdog decision'],
      ['--concurrency <n>', 'History processing concurrency'],
      ['--fast', 'Fast status/history mode'],
      ['--no-fast', 'Disable fast status mode'],
      ['--show-skill-candidates [view]', 'Show skill candidate rows'],
      ['--skill-candidate-view <view>', 'Skill candidate rendering mode'],
      ['--skill-candidate-limit <n>', 'Skill candidate row limit'],
      ['--draft-id <id>', 'Filter by draft target id'],
      ['--output <path>', 'Export output path'],
      ['--export-skill-candidate-patch-template', 'Export apply_patch templates'],
      ['--quality-failed-only', 'Only include failed quality sessions'],
      ['--quality-category <name>', 'Quality category filter'],
      ['--quality-category-prefix <name>', 'Quality category prefix filter'],
      ['--quality-category-prefix-mode <mode>', 'Quality prefix match mode'],
      ['--since <iso>', 'History lower bound timestamp'],
      ['--status <value>', 'Session status filter'],
      ['--preset <preset>', 'Rendering preset'],
      ['--interval-ms <n>', 'Watch refresh interval'],
    ],
  },
];
